### ISSUE TITLE
2022 - mismatches between metadata and data

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/ghg-processor#4]
Moved here from #2 thread

Metadata rows 20-23 (July 14) and 29-38 (July 11 and 12) don't have any corresponding data.

Quick spot check for July 11. Metadata file says 

7/11/22 | 13:37 | Gcrew_WC_1
-- | -- | --
7/11/22 | 13:55 | Gcrew_WC_2
7/11/22 | 14:19 | Gcrew_WC_3
7/11/22 | 14:12 | Gcrew_WC_4
7/11/22 | 14:28 | Gcrew_WC_5

but timestamps in the data file for 7/11 only run from 07:14 to 12:31.

FYI @wilsonsj100

**Comment by wilsonsj100** [comment]
Okay I found the problem with the times. I accidentally forgot to change the times from June to July when I input the data, so basically I had June put in twice. I am attaching the new metadata file here with the correct info for July. I went through and also double checked all the other months and they seem to be correct now. 
[COMPASS_ChamberFlux_Metadata_2022.xlsx](https://github.com/COMPASS-DOE/sw/files/10447245/COMPASS_ChamberFlux_Metadata_2022.xlsx)

**Comment by bpbond** [comment]
Fast detective work. Thank you! More soon.

**Comment by wilsonsj100** [comment]
Thank you for being patient!! I am still investigating the July data file - thinking I might just have Evan resend it to me.

**Comment by bpbond** [comment]
No worries, take your time to check and understand fully!

**Comment by bpbond** [comment]
We're good here—all mismatches resolved as far as I can see. 🎉
