### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/ghg-processor#6]
After talking with @wilsonsj100 and @megonigalp today.

## Straightforward

- [x] Implement default dead band time and custom dead band (by observation in metadata)
- [x] Problem with CO2? flag associated methane observation
- [x] Polynomial model - at least fit and use R2 divergence from linear as a diagnostic
- [x] y-intercept as useful QA/QC

## Trickier

- [ ] Flag observations/fluxes below detection limit
- [ ] Identifying ebullition events - how? - possible before/after slope changes <-- a segmented model?

**Comment by wilsonsj100** [comment]
I think we should also consider adding into the beginning an addition of 10-30 secs to the start time as an equilibration time - i.e. to ensure equilibration of the tubing and closed chamber. This is another little things so not a big deal.

**Comment by bpbond** [comment]
@wilsonsj100 I've set up a standard QA/QC "compare two things" framework for this. Basically, first we plot column 1 versus column 2 and use standardized residuals to identify outliers. For example:

<img width="812" alt="Screenshot 2023-01-28 at 11 56 41 AM" src="https://user-images.githubusercontent.com/1956468/215279024-0a0652a5-740e-46ba-8115-5b1ac425dc23.png">

Then, we plot the potentially problematic observations in detail:

<img width="792" alt="Screenshot 2023-01-28 at 11 56 58 AM" src="https://user-images.githubusercontent.com/1956468/215279071-dae5e3d1-6ab9-4e4d-bba2-bae5ce03558d.png">

Feedback welcome!

**Comment by bpbond** [comment]
Nice, the polynomial test is correctly identifying a curvature problem in one observation:

<img width="386" alt="Screenshot 2023-01-28 at 12 05 23 PM" src="https://user-images.githubusercontent.com/1956468/215279409-4d6a788b-940d-46c0-9eb0-3cdfdca65248.png">

**Comment by bpbond** [comment]
Superseded by #11
