### ISSUE TITLE
Volume question

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/ghg-processor#8]
@wilsonsj100 

We're calculating flux based on the total chamber volume in the metadata file, but (usually) also want to account for the analyzer + tubing volume. Do you know what that is?

(Or does the volume column already include that?)

**Comment by wilsonsj100** [comment]
Hi Ben! 

Yes, good point. The tubing is such a small volume compared to the chamber that I just left it off, but we can add a column for tubing volume to the metadata and we can fill it out. That is probably the safest way to go. 

The tubing is 10ft long and inner diameter is 1/8inches. Transfer those into m you get length = 3.048m, inner diameter = 0.0381, and radius = 0.01905. So, if volume of a tube is Vol = pi * r2 * length, then the volume is: 0.00347499989 m3.

**Comment by bpbond** [comment]
Thanks! In addition to the tubing, there's also an internal volume of the analyzer...but as you say, these are minor compared to the chambers themselves.

Maybe the simplest thing to do is declare that the "Volume" column in the metadata file is TOTAL volume. If the user wants to add "Chamber_volume", "Tubing_volume", etc., that's fine, **but the code will only pay attention to `Volume`**. That good?

**Comment by wilsonsj100** [comment]
Yes, that sounds good. I am realizing now that we would want to double that calculated area because the tubing goes to the machine and back to the chamber (2x 10ft). I can find out what the internal volume of the instrument is and add that to the metadata then we can just have the volume column be the sum of those other columns. 

Thanks! 
-Steph

**Comment by bpbond** [comment]
I've modified the Excel cell note to say
>Total system volume (chambers, tubing, and analyzer), in m2

**Comment by wilsonsj100** [comment]
sounds good thank you!

**Comment by wilsonsj100** [comment]
I think the above should say m3 - I accidentally put m2 and lead us astray

**Comment by wilsonsj100** [comment]
Licor 7810: Optical Cavity Volume: 6.41 cm3 so in m3 it is 6.41e-6 (0.00000641) m3.

**Comment by bpbond** [comment]
...which is _completely_ negligible. 😄 

Yes, the note in the Excel file originally said m2 too. Fixed.

**Comment by wilsonsj100** [comment]
ooops - gotta always check those units! 

Thank you :)
