### ISSUE TITLE
Issues to fix

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/ghg-processor#9]
- [x] Handle no metadata files present
- [x] Warn if a data file doesn't get matched at all
- [x] In plot_group function, color by gas (purple=co2, blue=ch4)
- [x] why is co2 intercept not going through ambient?
- [x] for twocol comparison, just have 1:1 line, not linear fit
- [x] Add sample driver script that calls the processor and then does something

**Comment by bpbond** [comment]
@wilsonsj100 

>why is co2 intercept not going through ambient?

Because we're doing the model fits using mmol/m2 for CO2 and µmol/m2 for CH4; i.e., we've already converted them to area-based. So the weird intercepts being reports are 'right' but they're in unexpected units.

**Comment by bpbond** [comment]
Alternatively we can fit the models to the machine concentrations (in ppm) versus time (seconds), which will produce intuitive intercepts and slopes. And then we'll need to do a final post-model conversion to produce final fluxes (and their errors) in xmol/m2/day.

Does that work @wilsonsj100 ? Lmk if you have a preference.

**Comment by wilsonsj100** [comment]
I think fitting the model to the machine concentrations could be a good idea. I don't see any problem with doing a post-model conversion to get the correct/wanted units and errors. Thank you!!!

**Comment by bpbond** [comment]
Gracias!
